version: "2"

linters:
  default: none
  enable:
    - bodyclose      # Checks HTTP response body is closed
    - copyloopvar    # Detects places where loop variables are copied
    - decorder
    - dupl
    - dupword        # Checks for duplicate words
    - errcheck
    - errorlint      # Problems with error wrapping (Go 1.13+)
    - gocritic
    - govet
    - ineffassign
    - noctx          # Finds sending http request without context.Context
    - nolintlint     # reports ill-formed or insufficient nolint directives
    - staticcheck
    - unconvert
    - unused
    - funcorder  # checks the order of functions, methods, and constructors
    - gocognit # computes and checks the cognitive complexity of functions
    - goconst # finds repeated strings that could be replaced by a constant
    - godoclint # checks Golang's documentation practice
    - godot # checks if comments end in a period
    - gomoddirectives # manages the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - goprintffuncname # checks that printf-like functions are named with f at the end
    - gosec # inspects source code for security problems
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - iface # checks the incorrect use of interfaces, helping developers avoid interface pollution
    - ineffassign # detects when assignments to existing variables are not used
    - intrange # finds places where for loops could make use of an integer range
    - iotamixing # checks if iotas are being used in const blocks with other non-iota declarations
    - loggercheck # checks key value pairs for common logger libraries (kitlog,klog,logr,zap)
    - makezero # finds slice declarations with non-zero initial length
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: false
      enable:
        - atomic
        - bools
        - buildtag
        - nilfunc
        - printf
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    decorder:
      dec-order:
        - const
        - var
        - type
        - func
      disable-dec-order-check: false
      disable-init-func-first-check: false
      disable-dec-num-check: false  # Allow multiple declarations of same type
    gocognit:
      # Minimal code complexity to report.
      # Default: 30
      min-complexity: 20
      test: false

  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
          - unparam
        text: "always nil"
      - path: 'cmd/'
        linters:
          - errcheck
      - path: 'main\.go'
        linters:
          - staticcheck
        text: "SA1019.*plugin.Debug"
      - linters:
          - staticcheck
        text: "SA1019.*Read is deprecated"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/iilei/phonid
    golines:
      max-len: 120

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  go: '1.25'
