[phonetic]
  patterns = ['CVCVCXCVCVC', 'CVCVCXCVCVCXCVCVCXCVCVC']

  [phonetic.placeholders]
    C = 'bdfghjklmnprstvz'
    V = 'aiou'
    X = '-'

[[preflight]]
  input = '2130706433'  # localhost IP address (127.0.0.1 = 2130706433)
  output = 'lusab-babad'
